stages:
  - build
  - test

variables:
  DOCKER_IMAGE: "my-app"
  DOCKER_TAG: "latest"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

build_docker:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker save $DOCKER_IMAGE:$DOCKER_TAG > my_app_image.tar
  artifacts:
    paths:
      - my_app_image.tar

test_docker:
  stage: test
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  dependencies:
    - build_docker
  script:
    - echo "Loading Docker image..."
    - docker load < my_app_image.tar
    - echo "Starting Docker container..."
    - docker run -d --name my-app -p 8080:80 $DOCKER_IMAGE:$DOCKER_TAG
    - echo "Testing with curl..."
    - sleep 5
    - curl -f http://localhost:8080 || (echo "Test failed" && exit 1)
  after_script:
    - docker stop my-app || true
    - docker rm my-app || true

